### ISSUE TITLE
No sign of it working

### ISSUE THREAD

**Issue by clawoflight** [pedrokost/STProjectPlanner#1]
First of all, thanks for this - I was looking for something like this!

Sadly, I can't tell if it is working. The plugin was installed through package control.
I tried `filename_projectplan.md` and `projectplan.md`, but nothing happens.
I also tried it with the exact layout from your example.

Any Idea what I may be missing?

I am running ST3 3083-2 on Arch Linux.

**Comment by pedrokost** [comment]
Hi @clawoflight 

the naming of the files should be: `<filename>.projectplan.md`

BTW, if you want it to look prettier, install also the "MarkdownEditing" plugin.

Alos, there might be some (quite a few) rough edges at the moment -- I'll be improving it over the next days, so please bear with me :)

**Comment by pedrokost** [comment]
I just realized I should update the README file. I just updated it.

If you need an example, please refer to the file `example.projectplan.md`

**Comment by clawoflight** [comment]
Thanks, it works now.

Yeah, there are a few things you could fix in the readme.

I am using `Markdown Extended` syntax and the `Afterglow - Markdown`
theme, works and looks great :)

## 

GPG fingerprint: 871F 1047 7DB3 DDED 5FC4 47B2 26C7 E577 EF96 7808

**Comment by pedrokost** [comment]
Good to hear, I will close the issue now.

Please, if you stumble upon other unclear parts of the README open a new issue.
