### ISSUE TITLE
### 2w weekly effort timeline does not work

### ISSUE THREAD

**Issue by pdanpdan** [pedrokost/STProjectPlanner#3]
Hello.
It seems I can't change the duration for ### Weekly effort timeline
Without a week number modifier it works.

**Comment by pedrokost** [comment]
I can confirm the bug, I will look into it this evening or tomorrow

**Comment by pedrokost** [comment]
Fixed in https://github.com/pedrokost/STProjectPlanner/commit/695b27f27e7ee8605829f894646297a68e703b41
