### ISSUE TITLE
Bug with dates

### ISSUE THREAD

**Issue by webtotma** [pedrokost/STProjectPlanner#7]
During the work you receive here so:

![Image](https://dl.dropboxusercontent.com/u/43394865/test.png)

The dates are calculated weird.

Win 8.1 x64 ST3(build 3095)

**Comment by pedrokost** [comment]
Hi @webtotma, could you try using lowercase `m` for months? Does this solve the problem?

The current implementation uses a lowercase `m`. In an future version this will be modified such that `M` will mean `month` and `m` will be `minute`.
