### ISSUE TITLE
Wrong Section summaries graph

### ISSUE THREAD

**Issue by phlekk** [pedrokost/STProjectPlanner#8]
Hi,

i don't see this ▄▂▁▁▁▁▁▁▁│▁▁▁▁▁▁▁▁▁▁▁▁▁│▁▁▁▁▁▁▁▁▁▁▄▂▄
i only see this (look at the pic).
![image](https://cloud.githubusercontent.com/assets/10845018/15149138/afacda34-16c8-11e6-9f66-0387ed5533cf.png)

Win 10 x64 ST3(build 3103)

Thanks for your help

**Comment by pedrokost** [comment]
Are you possibly using a special font?

**Comment by phlekk** [comment]
No special font.
I have tested some fonts.
It works with: Hack, Lucida Sans Unicode, Segoe UI Symbol

**Comment by pedrokost** [comment]
Thanks for the list. I will add it to the Readme, so that other people who have this issue try another font.
